package com.sys.pojo;

public class Customer {

    public Customer() {
    }

    public Customer(Integer usersId, String customerAddress) {
        this.usersId = usersId;
        this.customerAddress = customerAddress;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String customerAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.users_id
     *
     * @return the value of customer.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.users_id
     *
     * @param usersId the value for customer.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_address
     *
     * @return the value of customer.customer_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_address
     *
     * @param customerAddress the value for customer.customer_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerId=" + customerId +
                ", usersId=" + usersId +
                ", customerAddress='" + customerAddress + '\'' +
                '}';
    }
}