package com.sys.pojo;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer usersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_name
     *
     * @return the value of manager.manager_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_name
     *
     * @param managerName the value for manager.manager_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.users_id
     *
     * @return the value of manager.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.users_id
     *
     * @param usersId the value for manager.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    @Override
    public String toString() {
        return "Manager{" +
                "managerId=" + managerId +
                ", managerName='" + managerName + '\'' +
                ", usersId=" + usersId +
                '}';
    }
}