package com.sys.pojo;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer ordersId;

    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_entry_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersEntryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_payment_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersPaymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_delivery_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersDeliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_receiving_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersReceivingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_cancel_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersCancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_return_goods_start_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersReturnGoodsStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_return_goods_end_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersReturnGoodsEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_end_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_total_money
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Float ordersTotalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_consignee_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersConsigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_consignee_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersConsigneeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_consignee_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersConsigneePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_status
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_courier_number
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String ordersCourierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String shopsName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_id
     *
     * @return the value of orders.orders_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_id
     *
     * @param ordersId the value for orders.orders_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_entry_time
     *
     * @return the value of orders.orders_entry_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersEntryTime() {
        return ordersEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_entry_time
     *
     * @param ordersEntryTime the value for orders.orders_entry_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersEntryTime(String ordersEntryTime) {
        this.ordersEntryTime = ordersEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_payment_time
     *
     * @return the value of orders.orders_payment_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersPaymentTime() {
        return ordersPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_payment_time
     *
     * @param ordersPaymentTime the value for orders.orders_payment_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersPaymentTime(String ordersPaymentTime) {
        this.ordersPaymentTime = ordersPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_delivery_time
     *
     * @return the value of orders.orders_delivery_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersDeliveryTime() {
        return ordersDeliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_delivery_time
     *
     * @param ordersDeliveryTime the value for orders.orders_delivery_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersDeliveryTime(String ordersDeliveryTime) {
        this.ordersDeliveryTime = ordersDeliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_receiving_time
     *
     * @return the value of orders.orders_receiving_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersReceivingTime() {
        return ordersReceivingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_receiving_time
     *
     * @param ordersReceivingTime the value for orders.orders_receiving_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersReceivingTime(String ordersReceivingTime) {
        this.ordersReceivingTime = ordersReceivingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_cancel_time
     *
     * @return the value of orders.orders_cancel_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersCancelTime() {
        return ordersCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_cancel_time
     *
     * @param ordersCancelTime the value for orders.orders_cancel_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersCancelTime(String ordersCancelTime) {
        this.ordersCancelTime = ordersCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_return_goods_start_time
     *
     * @return the value of orders.orders_return_goods_start_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersReturnGoodsStartTime() {
        return ordersReturnGoodsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_return_goods_start_time
     *
     * @param ordersReturnGoodsStartTime the value for orders.orders_return_goods_start_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersReturnGoodsStartTime(String ordersReturnGoodsStartTime) {
        this.ordersReturnGoodsStartTime = ordersReturnGoodsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_return_goods_end_time
     *
     * @return the value of orders.orders_return_goods_end_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersReturnGoodsEndTime() {
        return ordersReturnGoodsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_return_goods_end_time
     *
     * @param ordersReturnGoodsEndTime the value for orders.orders_return_goods_end_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersReturnGoodsEndTime(String ordersReturnGoodsEndTime) {
        this.ordersReturnGoodsEndTime = ordersReturnGoodsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_end_time
     *
     * @return the value of orders.orders_end_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersEndTime() {
        return ordersEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_end_time
     *
     * @param ordersEndTime the value for orders.orders_end_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersEndTime(String ordersEndTime) {
        this.ordersEndTime = ordersEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_total_money
     *
     * @return the value of orders.orders_total_money
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Float getOrdersTotalMoney() {
        return ordersTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_total_money
     *
     * @param ordersTotalMoney the value for orders.orders_total_money
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersTotalMoney(Float ordersTotalMoney) {
        this.ordersTotalMoney = ordersTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_consignee_name
     *
     * @return the value of orders.orders_consignee_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersConsigneeName() {
        return ordersConsigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_consignee_name
     *
     * @param ordersConsigneeName the value for orders.orders_consignee_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersConsigneeName(String ordersConsigneeName) {
        this.ordersConsigneeName = ordersConsigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_consignee_address
     *
     * @return the value of orders.orders_consignee_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersConsigneeAddress() {
        return ordersConsigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_consignee_address
     *
     * @param ordersConsigneeAddress the value for orders.orders_consignee_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersConsigneeAddress(String ordersConsigneeAddress) {
        this.ordersConsigneeAddress = ordersConsigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_consignee_phone
     *
     * @return the value of orders.orders_consignee_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersConsigneePhone() {
        return ordersConsigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_consignee_phone
     *
     * @param ordersConsigneePhone the value for orders.orders_consignee_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersConsigneePhone(String ordersConsigneePhone) {
        this.ordersConsigneePhone = ordersConsigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_status
     *
     * @return the value of orders.orders_status
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersStatus() {
        return ordersStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_status
     *
     * @param ordersStatus the value for orders.orders_status
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersStatus(String ordersStatus) {
        this.ordersStatus = ordersStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_courier_number
     *
     * @return the value of orders.orders_courier_number
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getOrdersCourierNumber() {
        return ordersCourierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_courier_number
     *
     * @param ordersCourierNumber the value for orders.orders_courier_number
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersCourierNumber(String ordersCourierNumber) {
        this.ordersCourierNumber = ordersCourierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shops_name
     *
     * @return the value of orders.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getShopsName() {
        return shopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shops_name
     *
     * @param shopsName the value for orders.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsName(String shopsName) {
        this.shopsName = shopsName;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    @Override
    public String toString() {
        return "Orders{" +
                "ordersId=" + ordersId +
                ", ordersEntryTime='" + ordersEntryTime + '\'' +
                ", ordersTotalMoney=" + ordersTotalMoney +
                ", ordersConsigneeName='" + ordersConsigneeName + '\'' +
                ", ordersConsigneeAddress='" + ordersConsigneeAddress + '\'' +
                ", ordersConsigneePhone='" + ordersConsigneePhone + '\'' +
                ", ordersStatus='" + ordersStatus + '\'' +
                ", ordersCourierNumber='" + ordersCourierNumber + '\'' +
                ", shopsName='" + shopsName + '\'' +
                ", goodsName='" + goodsName + '\'' +
                '}';
    }
}