package com.sys.pojo;

public class Providers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.goods_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.goods_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String shopsName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.goods_id
     *
     * @return the value of providers.goods_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.goods_id
     *
     * @param goodsId the value for providers.goods_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.goods_name
     *
     * @return the value of providers.goods_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.goods_name
     *
     * @param goodsName the value for providers.goods_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.shops_name
     *
     * @return the value of providers.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getShopsName() {
        return shopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.shops_name
     *
     * @param shopsName the value for providers.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsName(String shopsName) {
        this.shopsName = shopsName;
    }
}