package com.sys.pojo;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchase_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.customer_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.orders_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer ordersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchase_amount
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer purchaseAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchase_id
     *
     * @return the value of purchase.purchase_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchase_id
     *
     * @param purchaseId the value for purchase.purchase_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.customer_id
     *
     * @return the value of purchase.customer_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.customer_id
     *
     * @param customerId the value for purchase.customer_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.orders_id
     *
     * @return the value of purchase.orders_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.orders_id
     *
     * @param ordersId the value for purchase.orders_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchase_amount
     *
     * @return the value of purchase.purchase_amount
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getPurchaseAmount() {
        return purchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchase_amount
     *
     * @param purchaseAmount the value for purchase.purchase_amount
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setPurchaseAmount(Integer purchaseAmount) {
        this.purchaseAmount = purchaseAmount;
    }
}