package com.sys.pojo;

public class Shops {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer shopsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.purchase_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String shopsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String shopsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String shopsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shops_email
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String shopsEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.users_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_id
     *
     * @return the value of shops.shops_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getShopsId() {
        return shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_id
     *
     * @param shopsId the value for shops.shops_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsId(Integer shopsId) {
        this.shopsId = shopsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.users_id
     *
     * @return the value of shops.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.users_id
     *
     * @param usersId the value for shops.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.purchase_id
     *
     * @return the value of shops.purchase_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.purchase_id
     *
     * @param purchaseId the value for shops.purchase_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_name
     *
     * @return the value of shops.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getShopsName() {
        return shopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_name
     *
     * @param shopsName the value for shops.shops_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsName(String shopsName) {
        this.shopsName = shopsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_address
     *
     * @return the value of shops.shops_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getShopsAddress() {
        return shopsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_address
     *
     * @param shopsAddress the value for shops.shops_address
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsAddress(String shopsAddress) {
        this.shopsAddress = shopsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_phone
     *
     * @return the value of shops.shops_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getShopsPhone() {
        return shopsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_phone
     *
     * @param shopsPhone the value for shops.shops_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsPhone(String shopsPhone) {
        this.shopsPhone = shopsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shops_email
     *
     * @return the value of shops.shops_email
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getShopsEmail() {
        return shopsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shops_email
     *
     * @param shopsEmail the value for shops.shops_email
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setShopsEmail(String shopsEmail) {
        this.shopsEmail = shopsEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.users_name
     *
     * @return the value of shops.users_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersName() {
        return usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.users_name
     *
     * @param usersName the value for shops.users_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }
}