package com.sys.pojo;

public class Turnover {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.turnover_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer turnoverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.use_users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer useUsersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.turnover_money
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Float turnoverMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.turnover_purpose
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String turnoverPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.turnover_type
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Short turnoverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.turnover_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String turnoverTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.turnover_id
     *
     * @return the value of turnover.turnover_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getTurnoverId() {
        return turnoverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.turnover_id
     *
     * @param turnoverId the value for turnover.turnover_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setTurnoverId(Integer turnoverId) {
        this.turnoverId = turnoverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.users_id
     *
     * @return the value of turnover.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.users_id
     *
     * @param usersId the value for turnover.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.use_users_id
     *
     * @return the value of turnover.use_users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUseUsersId() {
        return useUsersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.use_users_id
     *
     * @param useUsersId the value for turnover.use_users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUseUsersId(Integer useUsersId) {
        this.useUsersId = useUsersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.turnover_money
     *
     * @return the value of turnover.turnover_money
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Float getTurnoverMoney() {
        return turnoverMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.turnover_money
     *
     * @param turnoverMoney the value for turnover.turnover_money
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setTurnoverMoney(Float turnoverMoney) {
        this.turnoverMoney = turnoverMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.turnover_purpose
     *
     * @return the value of turnover.turnover_purpose
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getTurnoverPurpose() {
        return turnoverPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.turnover_purpose
     *
     * @param turnoverPurpose the value for turnover.turnover_purpose
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setTurnoverPurpose(String turnoverPurpose) {
        this.turnoverPurpose = turnoverPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.turnover_type
     *
     * @return the value of turnover.turnover_type
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Short getTurnoverType() {
        return turnoverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.turnover_type
     *
     * @param turnoverType the value for turnover.turnover_type
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setTurnoverType(Short turnoverType) {
        this.turnoverType = turnoverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.turnover_time
     *
     * @return the value of turnover.turnover_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getTurnoverTime() {
        return turnoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.turnover_time
     *
     * @param turnoverTime the value for turnover.turnover_time
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setTurnoverTime(String turnoverTime) {
        this.turnoverTime = turnoverTime;
    }
}