package com.sys.pojo;

public class Users {
    public Users() {
    }

    public Users(String usersName, String usersPassword) {
        this.usersName = usersName;
        this.usersPassword = usersPassword;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer usersId;
    private String address;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_sex
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_Email
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_password
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_head_icon
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String usersHeadIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_id
     *
     * @return the value of users.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_id
     *
     * @param usersId the value for users.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_name
     *
     * @return the value of users.users_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersName() {
        return usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_name
     *
     * @param usersName the value for users.users_name
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_sex
     *
     * @return the value of users.users_sex
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersSex() {
        return usersSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_sex
     *
     * @param usersSex the value for users.users_sex
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersSex(String usersSex) {
        this.usersSex = usersSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_phone
     *
     * @return the value of users.users_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersPhone() {
        return usersPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_phone
     *
     * @param usersPhone the value for users.users_phone
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersPhone(String usersPhone) {
        this.usersPhone = usersPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_Email
     *
     * @return the value of users.users_Email
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersEmail() {
        return usersEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_Email
     *
     * @param usersEmail the value for users.users_Email
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersEmail(String usersEmail) {
        this.usersEmail = usersEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_password
     *
     * @return the value of users.users_password
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersPassword() {
        return usersPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_password
     *
     * @param usersPassword the value for users.users_password
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_head_icon
     *
     * @return the value of users.users_head_icon
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getUsersHeadIcon() {
        return usersHeadIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_head_icon
     *
     * @param usersHeadIcon the value for users.users_head_icon
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersHeadIcon(String usersHeadIcon) {
        this.usersHeadIcon = usersHeadIcon;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String adress) {
        this.address = adress;
    }
}