package com.sys.pojo;

public class Wallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer walletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_account
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String walletAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_password
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private String walletPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet.wallet_balance
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    private Float walletBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_id
     *
     * @return the value of wallet.wallet_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_id
     *
     * @param walletId the value for wallet.wallet_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setWalletId(Integer walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.users_id
     *
     * @return the value of wallet.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.users_id
     *
     * @param usersId the value for wallet.users_id
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_account
     *
     * @return the value of wallet.wallet_account
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getWalletAccount() {
        return walletAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_account
     *
     * @param walletAccount the value for wallet.wallet_account
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setWalletAccount(String walletAccount) {
        this.walletAccount = walletAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_password
     *
     * @return the value of wallet.wallet_password
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public String getWalletPassword() {
        return walletPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_password
     *
     * @param walletPassword the value for wallet.wallet_password
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setWalletPassword(String walletPassword) {
        this.walletPassword = walletPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet.wallet_balance
     *
     * @return the value of wallet.wallet_balance
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public Float getWalletBalance() {
        return walletBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet.wallet_balance
     *
     * @param walletBalance the value for wallet.wallet_balance
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    public void setWalletBalance(Float walletBalance) {
        this.walletBalance = walletBalance;
    }
}