package com.sys.dao;

import com.sys.pojo.*;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int deleteByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    Manager selectByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int updateByPrimaryKey(Manager record);
}