package com.sys.dao;

import com.sys.pojo.*;

public interface ProvidersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int insert(Providers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int insertSelective(Providers record);
}