package com.sys.dao;

import com.sys.pojo.*;

public interface TurnoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int deleteByPrimaryKey(Integer turnoverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int insert(Turnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int insertSelective(Turnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    Turnover selectByPrimaryKey(Integer turnoverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int updateByPrimaryKeySelective(Turnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbggenerated Sun Aug 09 14:49:32 CST 2020
     */
    int updateByPrimaryKey(Turnover record);
}